name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test-unit:
    name: Test unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Setup node/yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install packages
        run: yarn

      - name: Run unit tests
        run: forge test --root contracts
  tests:
    name: Contract tests
    runs-on: ubuntu-8
    defaults:
      run:
        shell: bash
        working-directory: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        run: yarn install

      - name: Lint Contracts
        run: yarn solhint

      - name: Lint Test Scripts
        run: yarn lint:test

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn hardhat --network hardhat test test/contract/*.spec.ts

      - name: Interface compatibility
        run: yarn run test:compatibility

      - name: Test Storage Layouts
        run: yarn run test:storage

      - name: Run coverage
        run: yarn hardhat coverage --testfiles "test/contract/*.spec.ts"
